spring:
  datasource:
    #Cấu hình MYSQL
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/qlbh_mhsolution
    #Cấu hình Postgres
    postgres:
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      url: jdbc:postgres://localhost:5432/qlbh__mhsolution


    jpa:
      mysql:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
      postgresql:
        hibernate:
          ddl-auto: update
          dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true


logging:
  level:
    root: debug
server:
  port: 8088
  servlet:
    context-path: /mh_solution

jwt:
  singerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  valid-duration: 3000
  refreshable-duration: 3600